services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8001:8000
    volumes:
      - /srv/04ea4e75-ca71-4eda-916c-6fad9221f3a2/Data/YouTube:/youtube
      - /srv/dev-disk-by-uuid-e3b35892-f917-465b-baa7-93962772ed9f/AppData/tubearchivist:/cache
    environment:
      - ES_URL=http://192.168.80.2:9200   # needs protocol e.g. http and port
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=http://10.0.0.2/24 https://tube.racemiller.com         # set your host name
      - TA_USERNAME=racemiller           # your initial TA credentials
      - TA_PASSWORD=7508216              # your initial TA credentials
      - ELASTIC_PASSWORD=7508216         # set password for Elasticsearch
      - TZ=America/Denver                 # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /srv/dev-disk-by-uuid-e3b35892-f917-465b-baa7-93962772ed9f/AppData/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.16.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=7508216"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  es:
