 services:
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    networks:
      - arr-stack
    ports:
      - 8686:8686/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/Music/Regular Music:/music
      - ${DOWNLOADS}/completed/music:/data/completed/music
      - ${DOWNLOADS}/../Soulseek:/soulseek
      - ${APPDATA}/lidarr:/config
      - ${APPDATA}/lidarr/custom-services.d:/custom-services.d
      - ${APPDATA}/lidarr/custom-cont-init.d:/custom-cont-init.d
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  xmas-lidarr:
    container_name: xmas-lidarr
    image: linuxserver/lidarr:latest
    networks:
      - arr-stack
    ports:
      - 8585:8686/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/Music/Christmas Music:/music
      - ${DOWNLOADS}/completed/music:/data/completed/music
      - ${APPDATA}/xmaslidarr:/config
      - ${APPDATA}/lidarr/custom-services.d:/custom-services.d
      - ${APPDATA}/lidarr/custom-cont-init.d:/custom-cont-init.d
      - ${DOWNLOADS}/../Soulseek:/soulseek
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - arr-stack
    ports:
      - 7878:7878/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/Movies:/movies
      - ${DATA}/Other Movies:/other
      - ${DOWNLOADS}/completed/other:/downloads
      - ${APPDATA}/radarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr4k:
    container_name: radarr4k
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - arr-stack
    ports:
      - 4444:7878/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/4K Movies:/movies
      - ${DOWNLOADS}/completed/4K:/downloads
      - ${APPDATA}/radarr4k:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    networks:
      - arr-stack
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/TV Shows:/tv
      - ${DATA}/Cartoons:/cartoons
      - ${DOWNLOADS}/completed/other:/downloads
      - ${APPDATA}/sonarr:/config
      - ${APPDATA}/sonarr/custom-services.d:/custom-services.d
      - ${APPDATA}/sonarr/custom-cont-init.d:/custom-cont-init.d
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr4k:
    container_name: sonarr4k
    image: linuxserver/sonarr:latest
    networks:
      - arr-stack
    ports:
      - 8484:8989/tcp
    restart: unless-stopped
    volumes:
      - ${RECYCLE}:/recycle
      - ${DATA}/4K Shows:/tv
      - ${DATA}/4K Cartoons:/cartoons
      - ${DOWNLOADS}/completed/4K:/downloads
      - ${APPDATA}/sonarr4k:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks: 
      - arr-stack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/readarr:/config
      - ${DATA}/eBooks:/books
      - ${DOWNLOADS}/completed/books:/downloads
      - ${RECYCLE}:/recycle
    ports:
      - 8787:8787
    restart: unless-stopped
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      - arr-stack
    ports:
      - 13378:80
    volumes:
      - ${DATA}/eBooks:/audiobooks
      - ${APPDATA}/audiobookshelf/config:/config
      - ${APPDATA}/audiobookshelf/metadata:/metadata
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - arr-stack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - arr-stack
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped 

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - arr-stack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA}/Cartoons:/cartoons
      - ${DATA}/Movies:/movies
      - ${DATA}/TV Shows:/tv
      - ${APPDATA}/bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped

  huntarr-sonarr:
    image: huntarr/4sonarr:latest
    container_name: huntarr-sonarr
    restart: unless-stopped
    networks:
      - arr-stack
    ports:
      - 8988:8988
    volumes:
      - ${APPDATA}/huntarr-sonarr:/config
    environment:
      API_KEY: 999660b68c014e988c13d361348810d8
      API_URL: http://10.0.0.2:8989
      API_TIMEOUT: 60
      MONITORED_ONLY: true
      HUNT_MISSING_SHOWS: 1
      HUNT_UPGRADE_EPISODES: 0
      SLEEP_DURATION: 900
      STATE_RESET_INTERVAL_HOURS: 168
      DEBUG_MODE: false
      ENABLE_WEB_UI: true
      SKIP_FUTURE_EPISODES: true
      SKIP_SERIES_REFRESH: false
      COMMAND_WAIT_DELAY: 1
      COMMAND_WAIT_ATTEMPTS: 600
      MINIMUM_DOWNLOAD_QUEUE_SIZE: -1
      RANDOM_MISSING: true
      RANDOM_UPGRADES: true

  huntarr-lidarr:
    image: huntarr/4lidarr:2.0
    container_name: huntarr-lidarr
    restart: unless-stopped
    networks:
      - arr-stack
    environment:
      API_KEY: 9936906c812c465db0300e7965767ced
      API_URL: http://10.0.0.2:8686
      HUNT_MISSING_MODE: album
      HUNT_MISSING_ITEMS: 1
      HUNT_UPGRADE_ALBUMS: 1
      SLEEP_DURATION: 900
      RANDOM_SELECTION: true
      MONITORED_ONLY: true
      STATE_RESET_INTERVAL_HOURS: 168
      DEBUG_MODE: false

  huntarr-radarr:
    image: huntarr/4radarr:latest
    container_name: huntarr-radarr
    restart: unless-stopped
    networks:
      - arr-stack
    environment:
      API_KEY: e138a165dd234dcb86d324131b1c0d5e
      API_URL: http://10.0.0.2:7878
      API_TIMEOUT: 60
      MONITORED_ONLY: true
      SKIP_FUTURE_RELEASES: true
      HUNT_MISSING_MOVIES: 1
      HUNT_UPGRADE_MOVIES: 0
      SLEEP_DURATION: 900
      RANDOM_SELECTION: true
      STATE_RESET_INTERVAL_HOURS: 168
      DEBUG_MODE: false

  huntarr-readarr:
    image: huntarr/4readarr:latest
    container_name: huntarr-readarr
    restart: unless-stopped
    networks:
      - arr-stack
    environment:
      API_KEY: 7eb82755fe3f4fa3bce9ed0d2e1b81d9
      API_URL: http://10.0.0.2:8787
      API_TIMEOUT: 60
      MONITORED_ONLY: true
      SKIP_FUTURE_RELEASES: true
      HUNT_MISSING_BOOKS: 1
      HUNT_UPGRADE_BOOKS: 0
      SLEEP_DURATION: 900
      RANDOM_SELECTION: true
      REFRESH_AUTHOR: true
      STATE_RESET_INTERVAL_HOURS: 168
      DEBUG_MODE: false

 networks:
  arr-stack:
