services
  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ${APPDATA}/lidarr:/config
      - ${DATA}:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  slskd:
    image: slskd/slskd
    container_name: slskd
    hostname: slskd
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    volumes:
      - ${APPDATA}/slskd:/app
      - ${DOWNLOADS}:/data
    restart: unless-stopped

  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    hostname: soularr
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
      - SCRIPT_INTERVAL=300
    volumes:
      - ${DOWNLOADS}:/downloads
      - ${APPDATA}/soularr:/data
    restart: unless-stopped